# Example only. Do NOT commit real keys.
[bybit]
api_key = "YOUR_KEY"
api_secret = "YOUR_SECRET"

[binance]
api_key = "YOUR_KEY"
api_secret = "YOUR_SECRET"

[risk]
base_target_pct = 0.025  # 2.5% base risk target
min_target_pct = 0.020   # 2% minimum (professional minimum)
max_target_pct = 0.030   # 3% maximum (professional maximum)
use_dynamic = true       # Enable dynamic risk based on confidence

[stops]
# Professional stop-loss multipliers (2-4× ATR to avoid random swings)
k_sl_lev20 = 1.5  # High leverage: tighter stops but still professional
k_sl_lev15 = 1.8  # Medium-high leverage
k_sl_lev10 = 2.2  # Medium leverage
k_sl_low   = 2.5  # Low leverage: wider stops for better R:R

# Professional take-profit multipliers (2.5-4.5× ATR for better expectancy)
m_tp_lev20 = 3.0  # High leverage: conservative targets
m_tp_lev15 = 3.5  # Medium-high leverage
m_tp_lev10 = 4.0  # Medium leverage
m_tp_low   = 4.5  # Low leverage: aggressive targets

atr_trail_mult_initial = 2.0
atr_trail_mult_late    = 1.5

scaleout_r1 = 1.5
scaleout_r2 = 3.0
scaleout_frac1 = 0.4
scaleout_frac2 = 0.3
leave_runner_frac = 0.3

[vol]
blend_w_garch = 0.30
blend_w_har   = 0.40
blend_w_atr   = 0.30
garch_har_outlier_ratio = 2.0
horizon_hours = 4

[portfolio]
corr_lookback_days = 60
corr_threshold = 0.7
cluster_risk_cap_pct = 0.5
